### ISSUE TITLE
markdown incorrectly parses text marked as italics

### ISSUE THREAD

**Issue by mehlian** [Ivo-Balbaert/The_Way_to_Jai#1]
When three underscores are used then text is incorrectly displayed on github.

Look "`See _31.1_.jai_:`" 
at 
https://github.com/Ivo-Balbaert/The_Way_to_Jai/blob/main/book/31_Working%20with%20threads.md

Probably same issue is with even number of underscores but it is unnoticeable.

Cheers

**Comment by Ivo-Balbaert** [comment]
Thanks for your remark. Yes it is a bit strange, 4 _ show the text in italic in this section, 3 do not.
I'll keep an eye out for other such examples, and will do a general review of all cases once I am satisfied with the text.

**Comment by mehlian** [comment]
The dot character breaks italic decoration (`_.`).
You can use asterisk character to get same visual results: `See *31.1_.jai*:`

See *31.1_.jai*:

I'm not sure where you want to render your text, different markdown engines may show text in different way.

**Comment by Ivo-Balbaert** [comment]
Thanks mehlian, I will use *  * ! I will leave this issue open until I have corrected all instances. Any other remarks are welcome.

**Comment by Ivo-Balbaert** [comment]
WIth your solution, I made a global correction for the issue. It can now be closed.
