### ISSUE TITLE
The Meaning of JAI

### ISSUE THREAD

**Issue by ramin-asadi-2021** [Ivo-Balbaert/The_Way_to_Jai#14]
Hi. 

This is probably a very silly bug report but I thought you might find it interesting.

I am not Jonathan Blow so I cannot be 100% certain, BUT....

Judging by Jonathan Blows character, given that he is a designer of puzzle games(notice how secretive he is about the name, not answering any questions about the name, so the name is a puzzle and is a very cool one), and that he has said several times that the name of a language is not important and that one should not spend his time coming up with cool names, I guess that JAI means "**Just An Identifier**".

 His thought process was probably something like... "what should I name this? Man, I don't want to waste my time like an idiot coming up with cool names... mmmm. I just need an identifier, cause a name is just an identifier..... just an identifier.... ahaaaa......JAI."

(I mentioned this about one or two years ago in reddit as well)

**Comment by Ivo-Balbaert** [comment]
The explanation you give is very credible, thanks. I added it to the text.
